### ISSUE TITLE
Crash on reopening the dialog.

### ISSUE THREAD

**Issue by 316karan** [dmfs/color-picker#1]
Hey, 

Whenever I reopen the Dialog after selecting or canceling the first time, the app crashes.

Stack trace : 

java.lang.NullPointerException
            at android.support.v4.app.FragmentManagerImpl.getFragment(FragmentManager.java:585)
            at android.support.v4.app.FragmentStatePagerAdapter.restoreState(FragmentStatePagerAdapter.java:211)
            at org.dmfs.android.view.ViewPager.onRestoreInstanceState(ViewPager.java:1288)
            at android.view.View.dispatchRestoreInstanceState(View.java:11910)
            at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:2584)
            at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:2590)
            at android.view.View.restoreHierarchyState(View.java:11888)
            at android.support.v4.app.Fragment.restoreViewState(Fragment.java:465)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:979)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1136)
            at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:739)
            at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1499)
            at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:456)
            at android.os.Handler.handleCallback(Handler.java:615)
            at android.os.Handler.dispatchMessage(Handler.java:92)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:4899)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:791)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:558)
            at dalvik.system.NativeStart.main(Native Method)

Could you please guide me how to solve this.

Thanks

**Comment by dmfs** [comment]
How do you call the dialog? Do you do anything with the fragment after the dialog is closed?

Can you reproduce the same issue with the demo project?

**Comment by 316karan** [comment]
Hey, 

I'm really sorry couldn't reply back before. I was able to solve this error by re-instantiating the dialog on click (as in the demo)

Thank you.

**Comment by dmfs** [comment]
Thanks for the feedback. I'm glad you could solve it.
